<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net472</TargetFramework>
		<RootNamespace>Synchronous</RootNamespace>
		<Nullable>disable</Nullable>
		<LangVersion>12</LangVersion>
		<OutputPath>..\..\1.6\Assemblies</OutputPath>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
		<AppendConfigurationToOutputPath>false</AppendConfigurationToOutputPath>
		<DebugType>embedded</DebugType>
	</PropertyGroup>

	<PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
		<Optimize>true</Optimize>
	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Client\GameClient.csproj" />
	  <ProjectReference Include="..\Shared\Shared.csproj" />
	  <ProjectReference Include="..\TCPNetwork\TCPNetwork.csproj" />
	</ItemGroup>
</Project>
