apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ template "rimworld-together.fullname" . }}-{{ .Values.ingress.topLevelDomain }}"
spec:
  secretName: "{{ template "rimworld-together.fullname" . }}-{{ .Values.ingress.shortenedDomain }}"
  issuerRef:
    name: "{{ template "rimworld-together.fullname" . }}-letsencrypt-prod"
    kind: ClusterIssuer
  commonName: "{{ .Values.ingress.hostname }}"
  dnsNames:
    - "{{ .Values.ingress.hostname }}"