apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "rimworld-together.fullname" . }}-pvc
  labels:
    {{- include "rimworld-together.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
