apiVersion: v1
kind: Service
metadata:
  name: {{ include "rimworld-together.fullname" . }}
  labels:
    {{- include "rimworld-together.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: game
      protocol: TCP
      name: game
  selector:
    {{- include "rimworld-together.selectorLabels" . | nindent 4 }}