# Currently broken due to GitHub Actions not being able to build Shared project
# Please find a way to fix it soon

name: Project Build

on: [push]

jobs:
  build-server:
    strategy:
      matrix:
        version:
          - 8.0.x
        os: 
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet ${{ matrix.version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{matrix.version}}
      - name: Build Shared
        run: make build-shared
      - name: Build Network
        run: make build-network
      - name: Build Server
        run: make build-server
      - name: Build Client
        run: make build-client

